DEFAULT_TASKS = [
    "STS12",
    "STS13",
    "STS14",
    "STS15",
    "STS16",
    "STS17",
    "STSBenchmark",
    "SICK-R",
]

DEFAULT_CANDIDATE_LANGUAGES = [
    "eng_Latn",
    "zho_Hans",
    "fra_Latn",
    "deu_Latn",
    "spa_Latn",
    "rus_Cyrl",
    "arb_Arab",
    "jpn_Jpan",
    "kor_Hang",
    "ita_Latn",
    "por_Latn",
    "hin_Deva",
]

LANGUAGE_ALIASES = {
    "en": "eng_Latn",
    "eng": "eng_Latn",
    "eng_latn": "eng_Latn",
    "zh": "zho_Hans",
    "zho": "zho_Hans",
    "zh-cn": "zho_Hans",
    "zho_hans": "zho_Hans",
    "fr": "fra_Latn",
    "fra": "fra_Latn",
    "fra_latn": "fra_Latn",
    "de": "deu_Latn",
    "deu": "deu_Latn",
    "deu_latn": "deu_Latn",
    "es": "spa_Latn",
    "spa": "spa_Latn",
    "spa_latn": "spa_Latn",
    "ru": "rus_Cyrl",
    "rus": "rus_Cyrl",
    "rus_cyrl": "rus_Cyrl",
    "ar": "arb_Arab",
    "arb": "arb_Arab",
    "arb_arab": "arb_Arab",
    "ja": "jpn_Jpan",
    "jpn": "jpn_Jpan",
    "jpn_jpan": "jpn_Jpan",
    "ko": "kor_Hang",
    "kor": "kor_Hang",
    "kor_hang": "kor_Hang",
    "it": "ita_Latn",
    "ita": "ita_Latn",
    "ita_latn": "ita_Latn",
    "pt": "por_Latn",
    "por": "por_Latn",
    "por_latn": "por_Latn",
    "hi": "hin_Deva",
    "hin": "hin_Deva",
    "hin_deva": "hin_Deva",
}

VALID_PROMPT_SETTINGS = {"english", "language-specific"}
VALID_SEMANTIC_VECTORS = {"source", "mean"}
REPRESENTATION_NAME = "attention_sum"
